Serie/config/routes.rb
Serie::Application.routes.draw do
 
  root to: 'static_pages#home'

   
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/privacy', to: 'static_pages#privacy'
  match '/terms', to: 'static_pages#terms'
  

end

Serie/app/models/nombre_del_modelo.rb
class NombreDelModelo
  include MongoMapper::Document


end

Serie/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def Privacy
  end
  
  def Home
  end

  def Help
  end

  def About
  end

  def Terms
  end

end

Serie/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Serie/app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
  	<h1>-----  Soy el footer ------ </h1>
  </nav>
</footer>

    

Serie/app/views/layouts/_header.html.erb
<header>
	<div class="navbar navbar-fixed-top">  
      <div class="navbar-inner">  
        <div class="container-fluid">  
    <!--   <img alt="logo" src="ull.jpg" /> --> 
          <div class="nav-collapse">  
            <ul class="nav">  
				<li class="active"><a href="#">Home</a></li>  
				 <li><%= link_to "Home",    root_path %></li>
          		<li><%= link_to "Help",    help_path %></li>
            </ul>  
            <p class="navbar-text pull-right">Logged in as <a href="#">username</a></p>  
          </div><!--/.nav-collapse -->  
        </div>  
      </div>  
    </div>  
</header>
 

Serie/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
 
 <%= stylesheet_link_tag 'bootstrap/css/bootstrap', :media => 'screen' %>
 <%= stylesheet_link_tag 'style', :media => 'screen' %>

Serie/app/views/layouts/application.html.erb
<!DOCTYPE html>  
<html lang="en">  
  <head>  
    <meta charset="utf-8">  
    <title>Series ULL</title>  
    <meta name="viewport" content="width=device-width, initial-scale=1.0">  
   
    <!-- Styles -->  
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  
 <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

 

Serie/app/views/static_pages/About.html.erb
<h1>StaticPages#About</h1>
<p>Find me in app/views/static_pages/About.html.erb</p>

Serie/app/views/static_pages/Help.html.erb
<h1>StaticPages#Help</h1>
<p>Find me in app/views/static_pages/Help.html.erb</p>

Serie/app/views/static_pages/Privacy.html.erb
<h1>StaticPages#Privacy</h1>
<p>Find me in app/views/static_pages/Privacy.html.erb</p>

Serie/app/views/static_pages/Terms.html.erb
<h1>StaticPages#Terms</h1>
<p>Find me in app/views/static_pages/Terms.html.erb</p>

Serie/app/views/static_pages/about.html.erb
<h1>StaticPages#About</h1>
<p>Find me in app/views/static_pages/About.html.erb</p>

Serie/app/views/static_pages/help.html.erb
<h1>StaticPages#Help</h1>
<p>Find me in app/views/static_pages/Help.html.erb</p>

Serie/app/views/static_pages/home.html.erb
 <div class="row-fluid">  
   	<div class="span3">  
   		<div class="well sidebar-nav">  
       		<ul class="nav nav-list">  
       			<li class="nav-header">Nuestros Servicios</li>  
	            <li><a href="#">Series</a></li>  
	            <li><a href="#">Peliculas</a></li>  
	            <li><a href="#">Lalala</a></li>  
	            <li><a href="#">lalala</a></li>  
	            <li class="nav-header">&Uacuteltimas Novedades</li>
				<li><a href="#">Series</a></li>  
	            <li><a href="#">Pel&iacuteculas</a></li>  
	            <li><a href="#">Lalala</a></li>  
	            <li><a href="#">lalala</a></li>  
       		</ul>  
    	</div><!--/.well -->  
    </div><!--/span-->  
    <div class="span9">  
       	<div class="leaderboard">  
           	<h1>Series, Pel&iacuteculas, Cortos, Documentales y m&aacutes </h1>  
           	<p> Lalalalla lalalal En esta pagina podras lalala lalal lalal alalal alalal </p>  
           	<p><a class="btn btn-success btn-large"> Entra ya! </a></p>  
       	</div>  
       	<div class="row-fluid">  
           	<div class="span4">  
				<h2>Pelis</h2> 
				<img id="img_init" src="http://lorempixel.com/150/190/sports">			  
				<p> Las mejores pelis del mundo mundial y mucho m&aacutes! </p>  
				<p><a class="btn btn-success btn-large" href="#"> Mira algunas de las que tenemos</a></p>  
           	</div><!--/span-->  
           	<div class="span4">  
				<h2>Series</h2>  
				<img id="img_init" src="http://lorempixel.com/150/190/abstract">
				<p> Las mejores series del mundo mundial y mucho m&aacutes! </p>  
				<p><a class="btn btn-success btn-large" href="#">Mira algunas de las que tenemos </a></p>  
           	</div><!--/span-->  
           	<div class="span4">  
				<h2>Cortos</h2>  
				<img id="img_init" src="http://lorempixel.com/150/190/food">
				<p>Los mejores cortos del mundo mundial y mucho m&aacutes! </p>  
				<p><a class="btn btn-success btn-large" href="#">Mira algunos de los que tenemos</a></p>  
           	</div><!--/span-->  
       	</div><!--/row-->  
   	</div><!--/span-->
</div><!--/row-fluid--> 	

Serie/app/views/static_pages/privacy.html.erb
<h1>StaticPages#Privacy</h1>
<p>Find me in app/views/static_pages/Privacy.html.erb</p>

Serie/app/views/static_pages/terms.html.erb
<h1>StaticPages#Terms</h1>
<p>Find me in app/views/static_pages/Terms.html.erb</p>